// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protobufs/discuss/discuss.proto

package pdiscuss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewArgumentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Argument      string  `protobuf:"bytes,1,opt,name=Argument,proto3" json:"Argument,omitempty"`
	ResponseTo    *int32  `protobuf:"varint,2,opt,name=ResponseTo,proto3,oneof" json:"ResponseTo,omitempty"`
	ArgumentStart *int32  `protobuf:"varint,3,opt,name=ArgumentStart,proto3,oneof" json:"ArgumentStart,omitempty"`
	ArgumentEnd   *int32  `protobuf:"varint,4,opt,name=ArgumentEnd,proto3,oneof" json:"ArgumentEnd,omitempty"`
	Token         string  `protobuf:"bytes,5,opt,name=Token,proto3" json:"Token,omitempty"`
	Tags          []int32 `protobuf:"varint,6,rep,packed,name=Tags,proto3" json:"Tags,omitempty"`
	Title         *string `protobuf:"bytes,7,opt,name=title,proto3,oneof" json:"title,omitempty"`
}

func (x *NewArgumentRequest) Reset() {
	*x = NewArgumentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewArgumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewArgumentRequest) ProtoMessage() {}

func (x *NewArgumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewArgumentRequest.ProtoReflect.Descriptor instead.
func (*NewArgumentRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{0}
}

func (x *NewArgumentRequest) GetArgument() string {
	if x != nil {
		return x.Argument
	}
	return ""
}

func (x *NewArgumentRequest) GetResponseTo() int32 {
	if x != nil && x.ResponseTo != nil {
		return *x.ResponseTo
	}
	return 0
}

func (x *NewArgumentRequest) GetArgumentStart() int32 {
	if x != nil && x.ArgumentStart != nil {
		return *x.ArgumentStart
	}
	return 0
}

func (x *NewArgumentRequest) GetArgumentEnd() int32 {
	if x != nil && x.ArgumentEnd != nil {
		return *x.ArgumentEnd
	}
	return 0
}

func (x *NewArgumentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NewArgumentRequest) GetTags() []int32 {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NewArgumentRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type NewArgumentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Error int32 `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *NewArgumentResponse) Reset() {
	*x = NewArgumentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewArgumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewArgumentResponse) ProtoMessage() {}

func (x *NewArgumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewArgumentResponse.ProtoReflect.Descriptor instead.
func (*NewArgumentResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{1}
}

func (x *NewArgumentResponse) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NewArgumentResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{3}
}

func (x *Id) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type VoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{4}
}

func (x *VoteRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *VoteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Ok struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok int32 `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *Ok) Reset() {
	*x = Ok{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{5}
}

func (x *Ok) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

type ReadArgumentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ReadArgumentRequest) Reset() {
	*x = ReadArgumentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArgumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArgumentRequest) ProtoMessage() {}

func (x *ReadArgumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArgumentRequest.ProtoReflect.Descriptor instead.
func (*ReadArgumentRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{6}
}

func (x *ReadArgumentRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ReadArgumentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorID int32   `protobuf:"varint,1,opt,name=AuthorID,proto3" json:"AuthorID,omitempty"`
	Text     string  `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	Votes    int32   `protobuf:"varint,3,opt,name=Votes,proto3" json:"Votes,omitempty"`
	TagIDs   []int32 `protobuf:"varint,4,rep,packed,name=TagIDs,proto3" json:"TagIDs,omitempty"`
	Error    int32   `protobuf:"varint,5,opt,name=Error,proto3" json:"Error,omitempty"`
	Title    string  `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *ReadArgumentResponse) Reset() {
	*x = ReadArgumentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadArgumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArgumentResponse) ProtoMessage() {}

func (x *ReadArgumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArgumentResponse.ProtoReflect.Descriptor instead.
func (*ReadArgumentResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{7}
}

func (x *ReadArgumentResponse) GetAuthorID() int32 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

func (x *ReadArgumentResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReadArgumentResponse) GetVotes() int32 {
	if x != nil {
		return x.Votes
	}
	return 0
}

func (x *ReadArgumentResponse) GetTagIDs() []int32 {
	if x != nil {
		return x.TagIDs
	}
	return nil
}

func (x *ReadArgumentResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ReadArgumentResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ReadResponsesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArgumentID int32 `protobuf:"varint,1,opt,name=ArgumentID,proto3" json:"ArgumentID,omitempty"` // int32 Page = 2;
}

func (x *ReadResponsesRequest) Reset() {
	*x = ReadResponsesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponsesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponsesRequest) ProtoMessage() {}

func (x *ReadResponsesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponsesRequest.ProtoReflect.Descriptor instead.
func (*ReadResponsesRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{8}
}

func (x *ReadResponsesRequest) GetArgumentID() int32 {
	if x != nil {
		return x.ArgumentID
	}
	return 0
}

type Responses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReponsesIDs []int32 `protobuf:"varint,1,rep,packed,name=ReponsesIDs,proto3" json:"ReponsesIDs,omitempty"`
	Error       int32   `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *Responses) Reset() {
	*x = Responses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Responses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Responses) ProtoMessage() {}

func (x *Responses) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Responses.ProtoReflect.Descriptor instead.
func (*Responses) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{9}
}

func (x *Responses) GetReponsesIDs() []int32 {
	if x != nil {
		return x.ReponsesIDs
	}
	return nil
}

func (x *Responses) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

type ReadUserArgumentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username int32 `protobuf:"varint,1,opt,name=Username,proto3" json:"Username,omitempty"` // int32 Page = 2;
}

func (x *ReadUserArgumentsRequest) Reset() {
	*x = ReadUserArgumentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_discuss_discuss_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadUserArgumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUserArgumentsRequest) ProtoMessage() {}

func (x *ReadUserArgumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_discuss_discuss_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUserArgumentsRequest.ProtoReflect.Descriptor instead.
func (*ReadUserArgumentsRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_discuss_discuss_proto_rawDescGZIP(), []int{10}
}

func (x *ReadUserArgumentsRequest) GetUsername() int32 {
	if x != nil {
		return x.Username
	}
	return 0
}

var File_protobufs_discuss_discuss_proto protoreflect.FileDescriptor

var file_protobufs_discuss_discuss_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x63,
	0x75, 0x73, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x02, 0x0a, 0x12, 0x4e, 0x65, 0x77, 0x41,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0a, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x0a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x6f, 0x88, 0x01, 0x01, 0x12,
	0x29, 0x0a, 0x0d, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x0d, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x02, 0x52, 0x0b, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x54, 0x6f, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x41, 0x72, 0x67, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x22, 0x3b, 0x0a, 0x13, 0x4e, 0x65, 0x77, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x17,
	0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x22, 0x33, 0x0a,
	0x0b, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x14, 0x0a, 0x02, 0x4f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b, 0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x22,
	0xa0, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x6f, 0x74, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x54, 0x61, 0x67, 0x49, 0x44, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06,
	0x54, 0x61, 0x67, 0x49, 0x44, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x22, 0x36, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x43, 0x0a, 0x09, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x73, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x52, 0x65,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x49, 0x44, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x36, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x82, 0x05, 0x0a, 0x07, 0x44, 0x69, 0x73, 0x63,
	0x75, 0x73, 0x73, 0x12, 0x4a, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x1b, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x4e, 0x65, 0x77,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x72, 0x67,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4d, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x1c, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x67, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44,
	0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12,
	0x1d, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x64, 0x69, 0x73, 0x63,
	0x75, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x41, 0x72, 0x67, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64,
	0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x06,
	0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x12, 0x0c, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73,
	0x2e, 0x54, 0x61, 0x67, 0x1a, 0x0b, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x4f,
	0x6b, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x54, 0x61, 0x67, 0x12, 0x0b,
	0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x49, 0x64, 0x1a, 0x0c, 0x2e, 0x64, 0x69,
	0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x54, 0x61, 0x67, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x04, 0x56,
	0x6f, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x2e, 0x56, 0x6f,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09,
	0x2f, 0x70, 0x64, 0x69, 0x73, 0x63, 0x75, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protobufs_discuss_discuss_proto_rawDescOnce sync.Once
	file_protobufs_discuss_discuss_proto_rawDescData = file_protobufs_discuss_discuss_proto_rawDesc
)

func file_protobufs_discuss_discuss_proto_rawDescGZIP() []byte {
	file_protobufs_discuss_discuss_proto_rawDescOnce.Do(func() {
		file_protobufs_discuss_discuss_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_discuss_discuss_proto_rawDescData)
	})
	return file_protobufs_discuss_discuss_proto_rawDescData
}

var file_protobufs_discuss_discuss_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protobufs_discuss_discuss_proto_goTypes = []interface{}{
	(*NewArgumentRequest)(nil),       // 0: discuss.NewArgumentRequest
	(*NewArgumentResponse)(nil),      // 1: discuss.NewArgumentResponse
	(*Tag)(nil),                      // 2: discuss.Tag
	(*Id)(nil),                       // 3: discuss.Id
	(*VoteRequest)(nil),              // 4: discuss.VoteRequest
	(*Ok)(nil),                       // 5: discuss.Ok
	(*ReadArgumentRequest)(nil),      // 6: discuss.ReadArgumentRequest
	(*ReadArgumentResponse)(nil),     // 7: discuss.ReadArgumentResponse
	(*ReadResponsesRequest)(nil),     // 8: discuss.ReadResponsesRequest
	(*Responses)(nil),                // 9: discuss.Responses
	(*ReadUserArgumentsRequest)(nil), // 10: discuss.ReadUserArgumentsRequest
	(*emptypb.Empty)(nil),            // 11: google.protobuf.Empty
}
var file_protobufs_discuss_discuss_proto_depIdxs = []int32{
	0,  // 0: discuss.Discuss.NewArgument:input_type -> discuss.NewArgumentRequest
	6,  // 1: discuss.Discuss.ReadArgument:input_type -> discuss.ReadArgumentRequest
	8,  // 2: discuss.Discuss.ReadResponses:input_type -> discuss.ReadResponsesRequest
	10, // 3: discuss.Discuss.ReadUserArguments:input_type -> discuss.ReadUserArgumentsRequest
	11, // 4: discuss.Discuss.ReadLatestArguments:input_type -> google.protobuf.Empty
	11, // 5: discuss.Discuss.ReadLatestResponses:input_type -> google.protobuf.Empty
	2,  // 6: discuss.Discuss.AddTag:input_type -> discuss.Tag
	3,  // 7: discuss.Discuss.ReadTag:input_type -> discuss.Id
	4,  // 8: discuss.Discuss.Vote:input_type -> discuss.VoteRequest
	11, // 9: discuss.Discuss.GetTags:input_type -> google.protobuf.Empty
	1,  // 10: discuss.Discuss.NewArgument:output_type -> discuss.NewArgumentResponse
	7,  // 11: discuss.Discuss.ReadArgument:output_type -> discuss.ReadArgumentResponse
	9,  // 12: discuss.Discuss.ReadResponses:output_type -> discuss.Responses
	9,  // 13: discuss.Discuss.ReadUserArguments:output_type -> discuss.Responses
	9,  // 14: discuss.Discuss.ReadLatestArguments:output_type -> discuss.Responses
	9,  // 15: discuss.Discuss.ReadLatestResponses:output_type -> discuss.Responses
	5,  // 16: discuss.Discuss.AddTag:output_type -> discuss.Ok
	2,  // 17: discuss.Discuss.ReadTag:output_type -> discuss.Tag
	11, // 18: discuss.Discuss.Vote:output_type -> google.protobuf.Empty
	9,  // 19: discuss.Discuss.GetTags:output_type -> discuss.Responses
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_protobufs_discuss_discuss_proto_init() }
func file_protobufs_discuss_discuss_proto_init() {
	if File_protobufs_discuss_discuss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_discuss_discuss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewArgumentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewArgumentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ok); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArgumentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadArgumentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponsesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Responses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_discuss_discuss_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadUserArgumentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobufs_discuss_discuss_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_discuss_discuss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_discuss_discuss_proto_goTypes,
		DependencyIndexes: file_protobufs_discuss_discuss_proto_depIdxs,
		MessageInfos:      file_protobufs_discuss_discuss_proto_msgTypes,
	}.Build()
	File_protobufs_discuss_discuss_proto = out.File
	file_protobufs_discuss_discuss_proto_rawDesc = nil
	file_protobufs_discuss_discuss_proto_goTypes = nil
	file_protobufs_discuss_discuss_proto_depIdxs = nil
}
